let allRecipes = [
    {
        name:"Peeping Mushroom Pasta",
        img:"peeping mushroom",
        ingredients:["2 tablespoons butter", "1/4 cup all purpose flour", "2 cups lukewarm milk",
            "2 cups lukewarm milk", "1/4 onion", "1 whole clove", "1 bay leaf", "9 ounces rigatoni pasta", "Pinch of freshly ground nutmeg", "Sea salt and white pepper",
            "2 tablespoons whole-grain mustard", "3 1/2 ounces Gruyère, parmesan or other hard cheese", "6 ounces mixed enoki or shimeji mushrooms", "Finely chopped fresh parsley for serving"],
        instructions:["Melt the butter in a medium frying pan over medium heat. Add the flour and mix to form a paste, cooking it for 2 minutes. Remove from the heat and let cool for 2 minutes, then gradually add the milk, whisking continuously.",
            "Place the pan back over medium heat; add the onion, clove, and bay leaf; and simmer gently for 10 minutes, whisking frequently. If the sauce becomes too thick, whisk in a little more milk 1 tablespoon at a time until saucy.",
            "Preheat the oven to 350°F.", "Bring a stockpot of salted water to a boil. Put the pasta in the water and cook for 2 minutes less than the package instructions say.", "Finish the sauce by removing the onion, clove, and bay leaf, then adding the nutmeg and seasoning with salt and white pepper. Stir in the mustard and half the cheese.",
            "Drain the pasta and arrange the rigatoni pieces upright tightly in four ovenproof dishes; they will look a bit like honeycomb. Pour the sauce over the pasta. Tap the base of the baking dishes to allow the sauce to get between the holes, spooning more on if necessary. Place the mushroom stalks into the rigatoni holes, leaving the caps poking out. Sprinkle with the remaining cheese.",
            "Bake for 20 to 25 minutes, or until the cheese is golden and bubbling. Serve with a sprinkle of finely chopped parsley on top."],
    },
    {
        name:"Chorizo and Cheese Grilled Stuffed Bell Peppers",
        img:"chorizo and cheese",
        ingredients:["2 sweet potatoes", "1/2 cup apple cider vinegar", "1/2 cup brown sugar", "1 large can black beans", "1 cheap beer", 
            "1 tomato", "2 shallots", "2 jalapeños", "3 serrano peppers", "1 pound chorizo", "1/2 cup cotija cheese", "1/2 cup queso fresco", 
            "1 cup monterey jack cheese", "6 bell peppers (any color, but choose ones that can stand up straight)"],
        instructions:["Preheat oven to 400°F.", "Peel and dice the sweet potatoes.", "Toss the sweet potatoes with the brown sugar and apple cider vinegar (and some salt to taste).", 
            "Bake for 45 minutes, or until tender and browning at the edges; once finished, remove from oven and set aside to cool.", 
            "Chop shallots, tomato, and jalapeños for beans.", "Heat a small pot over medium heat.", 
            "Add the butter and the vegetables you just chopped and cook until they start to break down.", "Add the beans, beer and lime juice and stir well.", "Cover and cook on medium-low for about 20 minutes; when finished, set aside to cool.", 
            "While beans are cooking, heat skillet on medium-high heat.", "Remove chorizo from casing and add to skillet; cook until browned, then remove from heat and let cool.", 
            "De-seed and dice serranos.", "Mix sweet potatoes, beans, chorizo, serranos, and cheese together.", "Spark up your grill.", "Slice the tops of your bell peppers (save them), and remove core and seeds.", "While grill is very hot, grill peppers until they are just starting to get soft; you don't want to roast them all the way (grill the tops, too!).", 
            "Pull the peppers off, and fill them with your chorizo mixture; put the tops back on like little hats.", "Put peppers back on the grill around the edges of the coals, and cover.", 
            "Cook for 30 minutes, poking in every 5 minutes or so to spin peppers (part facing inward will cook fastest).",],
    },
    {
        name:"Beet Pickled Devlish Eggs",
        img:"beet eggs",
        ingredients:["2 serrano peppers", "3 cups water", "1 cup white vinegar", "1 1/2 cups sugar", "2 small beets", "3 cloves garlic", "3 bay leaves", "2 tablespoons whole black peppercorns", "1 tablespoon kosher salt", "12 large hard-boiled eggs", "2 tablespoons mayonnaise", 
            "1 tablespoon extra-virgin olive oil", "1 tablespoon Dijon-style mustard", "1 tablespoon Sriracha sauce", "Mild curry powder or smoked paprika for garnish"],
        instructions:["Cut 1 of the serrano peppers into halves lengthwise, retaining the seeds. Place the pepper in a large saucepan and add the water, vinegar, sugar, beets, garlic, bay leaves, peppercorns, and salt. Bring to a boil over high heat, reduce the heat to low, and simmer until the beets are tender, about 20 minutes. Remove the pot from the heat and let cool completely.",
            "Add the eggs to the beet liquid and refrigerate for at least 6 hours. Remove the eggs from the liquid and let them dry completely.",
            "Cut the eggs into halves lengthwise and remove the yolks. Place the yolks in a medium bowl and place the whites on a large plate. Add the mayonnaise, olive oil, mustard, and Sriracha to the yolks. Mix and mash to combine thoroughly. Fill the whites with the yolk mixture. Slice the remaining serrano pepper into rounds. Top each egg with a slice of serrano and a sprinkle of curry powder, if desired."],
    },
    {
        name:"Charred Brussels Sprouts with Spicy Anchovy Butter",
        img:"charred brussels",
        ingredients:["3 ounces best-quality anchovy fillet in oil, rinsed", "1 cup flat-leaf parsley", "1 teaspoon chili flakes", "1/4 pound unsalted butter", "1 garlic clove", 
            "sea salt", "1/2 teaspoon baking soda", "1 1/2 pounds brussels sprouts", "1/2 cup canola oil", "2 tablespoons fresh lemon juice", "2 tablespoons finely chopped chives"],
        instructions:["*spicy anchovy butter*", "Place all the ingredients in a food processor; puree until smooth and reserve. This makes more than is needed in the recipe, but it can be frozen for up to a month.", "*brussels sprouts*",
            "Fill a large bowl with salted ice water. Bring a large pot with about 3 quarts of water to a boil. Add the baking soda and enough salt to make the water salty like the sea.", 
            "Meanwhile, remove the outer leaves of the Brussels sprouts. Trim the ends off and split in half lengthwise. Carefully drop the Brussels sprouts into the boiling water and cook until tender, about 3 minutes. Drain immediately and immerse in the salted ice water to cool completely. Drain and pat dry with a paper towel. This can be done up to 1 day in advance.", 
            "In a large frying pan, heat the oil until it starts to smoke. Cook the Brussels sprouts, cut-side down, undisturbed, for 2-4 minutes, until they start to brown. Flip the Brussels sprouts and add the spicy anchovy butter; lower the heat to moderate and continue to cook until the butter melts, stirring occasionally. Season the Brussels sprouts with salt and finish with the lemon juice and chives."],
    },
    {
        name:"Crispy Corned Beef Fritters",
        img:"beef fritters",
    },
    {
        name:"Million Dollar Spaghetti",
        img:"spaghetti",
    }
    
]